phrase:
  project_id: 761225373f0a65c56010a06588f781db
  push:
    sources:
      - file: ./<locale_name>.xlf
        params:
          file_format: xlf
          locale_id: en
          update_translations: true
          autotranslate: true
  pull:
    targets:
      - file: ./<locale_name>.xlf
        params:
          file_format: xlf
